// Generated by Website Factory. Update via the factory pipeline, not by hand.

export interface MenuItem {
  name: string;
  native?: string;
  nr?: string;
  description?: string;
  price: string;
  spicy?: boolean;
  vegan?: boolean;
  note?: string;
}

export type MenuCategory = {
  id: string;
  label: string;
  native?: string;
  intro?: string;
  items: MenuItem[];
};

export const menuDataGeneratedFromFactory = true;

export const menuImageUrls: string[] = [
  "https://lh3.googleusercontent.com/p/AF1QipN66CwY4tzEYHmXppYjM143FDqm7lJeakhFlCg5=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGhvWV8bmBN9EtNZx12M5CKvhz5sYXjfyoKVndVBMgoQWVE1bbgHG5aFuLEcEYWgE7d68jUdDYtrlBmOWYl8AoAVQPBcnOHN6Mw3mAJxndnJh1dN2gJi-6e3CFu3zllCWXZBKA8_FpDDhxw=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFVci0OIng8n-j2uCryrDZCLIUQTfNjmVdVKkUyPQk5j7Bcklm2MwrMvjEuVnHwdzMBinWSeYhKmG8faBC_yQkjiFVPYmGaTnGbAipvZafcCt4kTFy1rvzbPXiQqj7mOJ_wEPDd51wsoeQ=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFhF4cs4DBrm8N-SrdeNRwzKcNgcnEOwpVKO72z-tdoRjYJ6t-glq4dcPmM4Ul8E18sNp9zo-mHPKnjhPoehImwdpx3Y90CMOpwxg8c46t2iBRtwBRuupNIyp7iGdihdoeN2b2kqwuDnEc=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFzVf7w8kD8EilZa1eY6CYDia3RXLi2Ttunce0o9uVfRkUELXO828I0LYQJ-J7HxBm9dNuBAJJGH5u28naUt0SgYjGZECbfp2_DJ6bP7t2z2vYC-ZgPpvxYZ6l5TATgibpQ605R943d1Gk6=w1600-h1200",
  "https://lh3.googleusercontent.com/p/AF1QipMs2zM63ODfFGbq-GBdHxtti25vZ5grxoiWQMI_=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF_dmWGNidDmv2-BnrzynBNxrJ7bFVMPJeygqK4lD2fQ1uMrcKA3GLfpPDoxMVOxiJE_4lFzqcx1DrbonQEesyvuuHrMNb7Pm-HEsnjChpccZdKbGtuzLvFuHogFl6PedGIYdSzi5r4NjA=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFdVFML9kEM0mZWVttcVsbKFxp3y2ANBwakURnxV-_aft32-FOaSR7w0nCeKNf_qDpHsfLmVnURuzOTrSYonkMYqCr7CcBNof5kUlf0GAmsu2m2-FrjLcL77IzzRDaspY2dWqco1Y2XJD0=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEMKLyMeypLlvrSTzZ1HfEST6pmCUuTjJ8PsMH7Qyguj2FfIR9nIJ0mKptOiok-3m94mzftgAlaWLdjktd429JADeqBQrhZmy0vyzMZ6mQdHC4k6HUZkAeYi3pGDe8A0kpZyNag2DDxRvlw=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG3miFBHN1EE8bKGWu8XuuI4goIoBxI9vPGx3TjfHvJjJzS7Wr8EkTOLMqsTdg4Gvu1cxnNGgc082-zMAg7dhgIDEZ5Edrw0nOHaCAhNUeRn1TEVBg32OzplbVMvfC9b3rNfLKjlm2orTqI=w1600-h1200",
  "https://lh3.googleusercontent.com/p/AF1QipM759bWU9LFWTeTiVtvZBLt_tOvcDygPQ9GEEOo=w1600-h1200",
  "https://lh3.googleusercontent.com/p/AF1QipPvvBZiA6EtmxxvvQd1imGkB9inpnuvY-mPJ-57=w1600-h1200",
  "https://lh3.googleusercontent.com/p/AF1QipPxxcs8kybhNT-gEWRy1AsLv6z2aPZdKGnXMGuB=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFnNiMg5UIJHjLn2RSmkVMtfDhNVUqhxy_5jgEZ60sBXApOF3fA7QPR_-EA37cqkrHMPNAbiFnh594_5WnZnbnTVCbMwGPG6rWoNNs4MG0bOAWapAHyAtL7uob5q_D4vwebdDOnHUr6qRgS=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGyjkHULq_6Kf3ZhQXGFotPphlD9_WRzkD8KDNRO4rJ_-NYCWA5JnMUFhV9v36EXXeGurCoivoeSJK97HgvdtUfRrWcfgWMgfevmUX6PLDhhzfn3tb4_np_Tj6oVOMe_7LNnkYWfRgAr-M=w1600-h1200"
];

export const menuCategories: MenuCategory[] = [
  {
    "id": "pasta",
    "label": "Pasta",
    "items": [
      {
        "name": "Lasagna",
        "description": "Rinderhackfleisch und käse überbacken (a,g)",
        "price": "9,00"
      },
      {
        "name": "Tris Di Pasta",
        "description": "Drei pastasorten mit tomatensoße- rinderhackfleisch und käse überbacken (a,z,g)",
        "price": "11,00"
      },
      {
        "name": "Rigatoni Al Forno",
        "description": "Rinderhackfleisch, tomatensoße und käse überbacken (a,z,g)",
        "price": "9,00"
      },
      {
        "name": "Pasta Alla Norma",
        "description": "Auberginen, tomatensoße und geriebener ricotta (g)",
        "price": "9,00"
      },
      {
        "name": "Rigatoni Gorgonzola",
        "description": "Gorgonzola-sahnecreme mit blattspinat (g,3)",
        "price": "9,00"
      },
      {
        "name": "Rigatoni Amalfitana",
        "description": "Tomaten-sahnesoße mit knoblauch und käse (a,z,g)",
        "price": "8,50"
      },
      {
        "name": "Rigatoni Puttanesca",
        "description": "Tomatensoße mit thunfisch, kapern und oliven (d,5)",
        "price": "9,50"
      },
      {
        "name": "Rigatoni Al Pomodoro",
        "description": "Tomatensoße",
        "price": "6,00"
      },
      {
        "name": "Spaghetti Bolognese",
        "description": "Tomaten-hackfleischsoße (a,z)",
        "price": "8,00"
      },
      {
        "name": "Rigatoni Primavera",
        "description": "Hinterschinken, erbsen und champignons in tomatensahnesoße (2,g)",
        "price": "9,00"
      },
      {
        "name": "Spaghetti Carbonara",
        "description": "Eigelb, guanciale und pecorino (c,2,3,g)",
        "price": "9,00"
      },
      {
        "name": "Spaghetti Aglio, Olio E Peperoncino",
        "description": "Knoblauch, olivenöl und pfefferschoten",
        "price": "8,00"
      },
      {
        "name": "Tortelloni Al Gorgonzola",
        "description": "Fleischtortelloni in gorgonzolasoße (a,g)",
        "price": "10,00"
      },
      {
        "name": "Tortelloni Al Prosciutto",
        "description": "Hinterschinken in sahnesoße (2,3,6,g)",
        "price": "10,00"
      }
    ]
  },
  {
    "id": "pizza-25-cm",
    "label": "Pizza 25 Cm",
    "items": [
      {
        "name": "Margherita",
        "description": "Tomatensoße und käse (g)",
        "price": "5,00"
      },
      {
        "name": "Prosciutto",
        "description": "Tomatensoße, käse und hinterschinken (2,3,6,g)",
        "price": "7,00"
      },
      {
        "name": "Romana",
        "description": "Tomatensoße, sardellen, käse und kapern (2,3,6,g)",
        "price": "7,00"
      },
      {
        "name": "Napoli",
        "description": "Tomatensoße, sardellen, käse, oliven und knoblauch (d,5,g)",
        "price": "7,00"
      },
      {
        "name": "Salami",
        "description": "Tomatensoße, käse und salami (1,g)",
        "price": "7,00"
      },
      {
        "name": "Tonno E Cipolla",
        "description": "Tomatensoße, käse, thunfisch und zwiebeln (d,g)",
        "price": "7,50"
      },
      {
        "name": "Funghi",
        "description": "Tomatensoße, käse und champignons",
        "price": "7,00"
      },
      {
        "name": "4 Formaggi",
        "description": "Vier verschiedene käsesorten (g)",
        "price": "8,00"
      },
      {
        "name": "4 Stagioni",
        "description": "Tomatensoße, käse, artischocken, champignons, salami und hinterschinken (1,2,3,6,g)",
        "price": "8,50"
      },
      {
        "name": "Diavola",
        "description": "Tomatensoße, käse und scharfe salami",
        "price": "8,50"
      },
      {
        "name": "Parma",
        "description": "Tomatensoße, käse, parmaschinken, rucola und parmesan (g)",
        "price": "9,00"
      },
      {
        "name": "Frutti Di Mare",
        "description": "Tomatensoße, meeresfrüchten, käse und knoblauch (d,g)",
        "price": "11,00"
      },
      {
        "name": "Salmone",
        "description": "Tomatensoße, lachs, blattspinat und knoblauch (d,g)",
        "price": "10,00"
      }
    ]
  },
  {
    "id": "salate",
    "label": "Salate",
    "items": [
      {
        "name": "Insalata Mista",
        "description": "Eisbergsalat, tomaten, gurken, zwiebeln",
        "price": "5,00"
      },
      {
        "name": "Insalata Primavera",
        "description": "Eisbergsalat, tomaten, gurken, karotten, zwiebeln",
        "price": "6,00"
      },
      {
        "name": "Insalata Tonno",
        "description": "Eisbergsalat, tomaten, gurken, eier, thunfisch, zwiebeln (d)",
        "price": "9,00"
      },
      {
        "name": "Insalata Prosciutto",
        "description": "Eisbergsalat, tomaten, gurken, eier, hinterschinken, zwiebeln und käse (2,3,6,g)",
        "price": "9,00"
      },
      {
        "name": "Insalata Pollo",
        "description": "Eisbergsalat, tomaten, gurken, mozzarella hähnchenbrustfilet, zwiebeln (g)",
        "price": "10,00"
      }
    ]
  },
  {
    "id": "dessert",
    "label": "Dessert",
    "items": [
      {
        "name": "Cannoli",
        "description": "Gefüllt mit ricottacreme (1, c, g)",
        "price": "3,00"
      },
      {
        "name": "Tiramisù",
        "description": "Hausgemacht (1, g, a, f, h, 7)",
        "price": "3,50"
      },
      {
        "name": "Salame Siciliano",
        "description": "(A, c, g)",
        "price": "4,00"
      },
      {
        "name": "Pizzabrot mit Nutella",
        "description": "(25 cm)",
        "price": "4,50"
      }
    ]
  },
  {
    "id": "getranke",
    "label": "Getränke",
    "items": [
      {
        "name": "Coca-Cola",
        "description": "0,33 l, 1 l",
        "price": "2,50"
      },
      {
        "name": "Coca-Cola Zero",
        "description": "0,33 l, 1 l",
        "price": "2,50"
      },
      {
        "name": "Sprite",
        "description": "0,33 l, 1 l",
        "price": "2,50"
      },
      {
        "name": "Mezzo Mix",
        "description": "0,33 l, 1 l",
        "price": "2,50"
      },
      {
        "name": "Fanta",
        "description": "0,33 l, 1 l",
        "price": "2,50"
      },
      {
        "name": "Redbull",
        "price": "3,00"
      },
      {
        "name": "Malzbier",
        "description": "0,33 l",
        "price": "3,00"
      }
    ]
  },
  {
    "id": "wein",
    "label": "Wein",
    "items": [
      {
        "name": "Lambrusco",
        "description": "Rot oder weiß (0,75 l)",
        "price": "12,00"
      },
      {
        "name": "Weißwein Trocken",
        "description": "0,75 l",
        "price": "12,00"
      },
      {
        "name": "Rotwein Trocken",
        "description": "0,75 l",
        "price": "12,00"
      }
    ]
  },
  {
    "id": "bier",
    "label": "Bier",
    "items": [
      {
        "name": "Bitburger",
        "price": "3,00"
      },
      {
        "name": "Becks",
        "price": "3,00"
      },
      {
        "name": "Heineken",
        "price": "3,00"
      },
      {
        "name": "Warsteiner Radler",
        "price": "3,00"
      }
    ]
  },
  {
    "id": "sonstiges",
    "label": "Sonstiges",
    "items": [
      {
        "name": "Knoblauch-Pizzabrot 25 Cm",
        "price": "2,50"
      }
    ]
  }
];
