// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type WeekdayHours = {
  day: string;
  time: string;
  closed: boolean;
};

export type RestaurantConfig = {
  name: string;
  shortName: string;
  tagline: string;
  logoGlyph: string;
  cuisine: string;
  website?: string;
  priceRange?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  nativeTagline: string;
  nativeTaglineTranslation: string;
  phone: string;
  phoneLink: string;
  landlinePhone?: string;
  landlinePhoneLink?: string;
  email: string;
  address: {
    street: string;
    cityLine: string;
    city: string;
  };
  mapsUrl: string;
  googleBusinessProfileUrl: string;
  socialMedia: {
    instagram: string;
    facebook: string;
    tiktok: string;
    hidden: {
      instagram: boolean;
      facebook: boolean;
      tiktok: boolean;
    };
    titleHidden: boolean;
  };
  closedDays: number[];
  closedDaysLabel: string;
  hours: WeekdayHours[];
  reservationTimeSlots: {
    startHour: number;
    endHour: number;
    stepMinutes: number;
    latestMinutes: number;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
    ogTitle: string;
    ogDescription: string;
    locale: string;
  };
  legal: {
    ownerName: string;
    vatId: string;
    responsiblePerson: string;
  };
};

export const restaurant: RestaurantConfig = {
  "name": "Peppe's Pasta",
  "shortName": "Peppe's Pasta",
  "tagline": "Italienisch",
  "logoGlyph": "P",
  "cuisine": "Italienisch",
  "nativeTagline": "",
  "nativeTaglineTranslation": "",
  "phone": "01575 7255307",
  "phoneLink": "tel:+4915757255307",
  "email": "",
  "address": {
    "street": "Hofstraße 1",
    "cityLine": "67065 Ludwigshafen am Rhein",
    "city": "Ludwigshafen am Rhein"
  },
  "mapsUrl": "https://maps.google.com/?cid=2103239191043004249&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "googleBusinessProfileUrl": "https://maps.google.com/?cid=2103239191043004249&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "socialMedia": {
    "instagram": "https://www.instagram.com/peppes_pasta/",
    "facebook": "https://www.facebook.com/p/Restaurant-Pizzeria-Tutto-Pasta-Ludwigshafen-am-Rhein-100078728535806",
    "tiktok": "https://tiktok.com/@peppespasta.ludwigshafenamrhein",
    "hidden": {
      "instagram": false,
      "facebook": false,
      "tiktok": true
    },
    "titleHidden": false
  },
  "closedDays": [
    2
  ],
  "closedDaysLabel": "Geschlossen: Dienstag.",
  "hours": [
    {
      "day": "Montag, Mittwoch, Donnerstag & Freitag",
      "time": "12:00–14:00 Uhr, 17:00–22:00 Uhr",
      "closed": false
    },
    {
      "day": "Dienstag",
      "time": "Geschlossen",
      "closed": true
    },
    {
      "day": "Samstag & Sonntag",
      "time": "17:00–22:00 Uhr",
      "closed": false
    }
  ],
  "reservationTimeSlots": {
    "startHour": 17,
    "endHour": 21,
    "stepMinutes": 30,
    "latestMinutes": 30
  },
  "seo": {
    "title": "Peppe's Pasta | Italienisch in Ludwigshafen am Rhein",
    "description": "Peppe's Pasta in Ludwigshafen am Rhein. italienische Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "keywords": [
      "Peppe's Pasta",
      "Italienisch Ludwigshafen am Rhein",
      "Peppe's Pasta Ludwigshafen am Rhein"
    ],
    "ogTitle": "Peppe's Pasta",
    "ogDescription": "Peppe's Pasta in Ludwigshafen am Rhein. italienische Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "locale": "de_DE"
  },
  "legal": {
    "ownerName": "",
    "vatId": "",
    "responsiblePerson": ""
  }
};

export function isClosedDay(dateStr: string): boolean {
  if (!dateStr) return false;
  const day = new Date(dateStr).getDay();
  return restaurant.closedDays.includes(day);
}

export function generateTimeSlots(): string[] {
  const startHour: number = restaurant.reservationTimeSlots.startHour;
  const endHour: number = restaurant.reservationTimeSlots.endHour;
  const stepMinutes: number = restaurant.reservationTimeSlots.stepMinutes;
  const latestMinutes: number = restaurant.reservationTimeSlots.latestMinutes;
  const slots: string[] = [];
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let minute = 0; minute < 60; minute += stepMinutes) {
      if (hour === endHour && minute > latestMinutes) break;
      const hh = hour.toString().padStart(2, "0");
      const mm = minute.toString().padStart(2, "0");
      slots.push(`${hh}:${mm}`);
    }
  }
  return slots;
}
