// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 22,
  "reviews": [
    {
      "author": "Luca Brück",
      "rating": 5,
      "text": "Super leckeres authentisches Italienisches Essen. Ging sehr schnell von Bestellung bis Abholung. Und vor allem sehr freundliches und zuvorkommendes Personal. Kann ich nur weiterempfehlen!",
      "time": "vor 3 Monaten"
    },
    {
      "author": "M&M Jambo-Gisbert",
      "rating": 5,
      "text": "Ich bin wirklich begeistert von Peppe’s Pasta! 😍\nDas Essen ist einfach super lecker – man schmeckt sofort die Qualität und die Liebe, mit der alles zubereitet wird. Die Preise sind absolut fair und mehr als angemessen für das, was man bekommt.\n\nBesonders toll finde ich, dass die Portionen immer richtig groß sind – man wird definitiv satt und bekommt wirklich viel für sein Geld!\n\nAber was mir am meisten in Erinnerung bleibt: Die Familie ist einfach unglaublich lieb und herzlich. Man fühlt sich direkt willkommen und gut aufgehoben. 🥰\n\nIch komme auf jeden Fall wieder und kann Peppe’s Pasta von Herzen weiterempfehlen!",
      "time": "vor 2 Monaten"
    },
    {
      "author": "Toni Nekaj",
      "rating": 5,
      "text": "Sehr sehr freundliches Personal. Und das Essen einfach nur wow. Sehr lecker und die Preise sind super fair.",
      "time": "vor 2 Monaten"
    },
    {
      "author": "nj a",
      "rating": 5,
      "text": "Der BESTE FOOD-TRUCK in ganz Ludwigshafen!!!! Pizza und Pasta vom Feinsten😍😍😍 ich würde auch 10 Sterne vergeben! Inhaber super freundlich und hier wird jedes Gericht mit gaaaanz viel Liebe zubereitet! Für alle die ein kleines Stück Italien-Feeling auf dem Esstisch haben möchten ist Peppe's Pasta genau das Richtige!!!",
      "time": "vor 4 Monaten"
    },
    {
      "author": "Fener 1907",
      "rating": 5,
      "text": "Sehr leckeres essen. Ich bin seit Tag eins dabei. Kann es jedem empfehlen. Einfach mal die leckere Lasagne probieren. Oder mein Favorit,Pizza Parma, da wird sogar noch alles selbst gemacht. Frische zutaten und immer ein nettes Gespräch. Es macht spaß zu zugucken wie das alles auch zubereitet wird. Authentisch , ehrlich und preis Leistung Top. Sowas sieht man heutzutage ganz selten. Ich werde mindestens 1 mal die Woche kommen. Bis zum nächsten mal Pepe ♥️🔥",
      "time": "vor 4 Monaten"
    }
  ]
};
